# Copyright Statement:
#
# This software/firmware and related documentation ("MediaTek Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to MediaTek Inc. and/or its licensors.
# Without the prior written permission of MediaTek inc. and/or its licensors,
# any reproduction, modification, use or disclosure of MediaTek Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.
# MediaTek Inc. (C) 2020. All rights reserved.
#
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
# RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
# AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
# SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
# AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#
# The following software/firmware and/or related documentation ("MediaTek Software")
# have been modified by MediaTek Inc. All revisions are subject to any receiver's
# applicable license agreements with MediaTek Inc.
################################################################################
#
################################################################################

MTKCAM_OPT_PATH := $(TOP)/$(MTK_PATH_SOURCE)/hardware/mtkcam3/option

MTKCAM_OPT_PLAT          := $(call to-lower,$(MTKCAM_PLATFORM))
MTKCAM_OPT_PLAT_MK       := mtkcam_$(MTKCAM_OPT_PLAT).mk
MTKCAM_OPT_PLAT_MK_PATH  := $(MTKCAM_OPT_PATH)/$(MTKCAM_OPT_PLAT_MK)

MTKCAM_OPT_BOARD         := $(MTKCAM_TARGET_BOARD_PLATFORM)
MTKCAM_OPT_BOARD_MK      := mtkcam_$(MTKCAM_OPT_BOARD).mk
MTKCAM_OPT_BOARD_MK_PATH :=

sinclude $(MTKCAM_OPT_PLAT_MK_PATH)

ifneq ($(MTKCAM_OPT_BOARD),$(MTKCAM_OPT_PLAT))
MTKCAM_OPT_BOARD_MK_PATH := $(MTKCAM_OPT_PATH)/$(MTKCAM_OPT_BOARD_MK)
sinclude $(MTKCAM_OPT_BOARD_MK_PATH)
endif

MTKCAM_OPT_LIST :=
MTKCAM_OPT_LIST += PLATFORM
MTKCAM_OPT_LIST += MTK_PLATFORM
MTKCAM_OPT_LIST += TARGET_BOARD_PLATFORM
MTKCAM_OPT_LIST += MTKCAM_OPT_PLAT_MK_PATH
MTKCAM_OPT_LIST += MTKCAM_OPT_BOARD_MK_PATH

define print-mtkcam-option
$(foreach v,$(MTKCAM_OPT_LIST),\
  $(info mtkcam_opt: $(v)=$($(v))))
endef

