/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
 *     TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/
#ifndef BASE_SIZE_H_
#define BASE_SIZE_H_

#include <mtkcam3/feature/stereo/hal/StereoArea.h>

//===============================================================
//  StereoSize implementation
//===============================================================
// 4:3
// Horizontal: 512x384, 64x0, (32, 0), content 480x360
const StereoHAL::StereoArea STEREO_BASE_SIZE_4_3(544, 360, 64, 0, 32, 0);

#define CUSTOMIZE_RATIO_ALIGNMENT (StereoHAL::E_KEEP_WIDTH)
#define CUSTOMIZE_BUFFER_ALIGNMENT (8)
#define CUSTOMIZE_REFINE_NONE_SIZE (1)
#define CUSTOMIZE_SLANT_SIZE (1)

#ifdef CUSTOMIZE_REFINE_NONE_SIZE
// 4:3
// Horizontal: 512x384, 64x0, (32, 0), content 480x360
// Notice: MAX content size: 640, max padding: 32 for each side(total 64)
const StereoHAL::StereoArea STEREO_BASE_SIZE_4_3_REFINE_NONE(544, 360, 64, 0, 32, 0);
#endif

#ifdef CUSTOMIZE_SLANT_SIZE
// 4:3
// Horizontal: 512x336, 64x0, (32, 0), content 448x336
// Notice: MAX content size: 640, max padding: 32 for each side(total 64)
const StereoHAL::StereoArea STEREO_BASE_SIZE_4_3_SLANT(512, 336, 64, 0, 32, 0);
#endif

#endif