# Copyright Statement:
#
# This software/firmware and related documentation ("MediaTek Software") are
# protected under relevant copyright laws. The information contained herein
# is confidential and proprietary to MediaTek Inc. and/or its licensors.
# Without the prior written permission of MediaTek inc. and/or its licensors,
# any reproduction, modification, use or disclosure of MediaTek Software,
# and information contained herein, in whole or in part, shall be strictly prohibited.
# MediaTek Inc. (C) 2020. All rights reserved.
#
# BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
# THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
# RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
# AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
# NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
# SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
# SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
# THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
# THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
# CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
# SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
# STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
# CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
# AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
# OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
# MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
#
# The following software/firmware and/or related documentation ("MediaTek Software")
# have been modified by MediaTek Inc. All revisions are subject to any receiver's
# applicable license agreements with MediaTek Inc.
################################################################################
#
################################################################################

#Please order by alphabet
MTKCAM_OPT_AINR := yes
MTKCAM_OPT_AINR_VERSION := 2.0
MTKCAM_OPT_CAM_DEV_TIMEOUT := 500
MTKCAM_OPT_CAP_MFLL_APPLY_RAW_BSS := yes
MTKCAM_OPT_CCAP_HIDL := no
MTKCAM_OPT_DCE_HFG := yes
MTKCAM_OPT_DSDN25 := yes
MTKCAM_OPT_FDFT_DIR := 5.0
MTKCAM_OPT_FDFT_SUB_VERSION := 2
MTKCAM_OPT_FDFT_USE_HW := 1
MTKCAM_OPT_FDVER := 50
MTKCAM_OPT_FD_PERIOD := 33
MTKCAM_OPT_ISP_VER := 65
MTKCAM_OPT_MAPPING_MGR := yes
MTKCAM_OPT_MDPQOS := yes
MTKCAM_OPT_MFLL_MF_TAG_VERSION := 14
MTKCAM_OPT_MSNR := yes
MTKCAM_OPT_MSNR_VER := 1.0
MTKCAM_OPT_MSTREAM := yes
MTKCAM_OPT_STAGGER := yes
MTKCAM_OPT_P1_HW_MARGIN := 12
MTKCAM_OPT_P2_AND_DEPTH := yes
MTKCAM_OPT_PQ_SIZE := 2
MTKCAM_OPT_RAW_FORMAT_UTILITY := yes
MTKCAM_OPT_REDUCE_GRALLOC_VA := yes
MTKCAM_OPT_SWNR := no
MTKCAM_OPT_VER4_5_PLATFORMS := yes
MTKCAM_OPT_REDUCE_GRALLOC_VA := yes

# VSDoF
MTKCAM_OPT_VSDOF_HAS_P1YUV := 6
MTKCAM_OPT_VSDOF_HAS_WPE := 1
MTKCAM_OPT_VSDOF_HAS_HW_DPE := 3
MTKCAM_OPT_VSDOF_HAS_AIDEPTH := 1
MTKCAM_OPT_VSDOF_HAS_VAIDEPTH := 1
MTKCAM_OPT_VSDOF_HAS_ISP_FE_TUNING := 1
MTKCAM_OPT_VSDOF_HAS_P1_RESIZE_QUALITY := 1
MTKCAM_OPT_VSDOF_HW_CONF_FORMAT := 2
